// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bloofbyxjnzgvqfmwwag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsb29mYnl4am56Z3ZxZm13d2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NDM2NTAsImV4cCI6MjA2NTAxOTY1MH0.EjqYyTrDpXPTlczlrYNgd7OUA_m_gC-l38IUMnznNNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);